@echo off
echo Fine-tuning on 3K dataset...
python scripts/train.py --config configs/train.yaml --experiment "Full SignalScope model 3K" --resume artifacts/models/full_signalscope_model/best_model.pt
echo Comparing models...
python scripts/compare_models.py
